### ISSUE TITLE
[meta] Repo improvements / We could better utilise GitHub

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/BizHawk#1420]
* [x] Projects disabled
* [x] Wiki disabled
* [x] Milestones created
* ~~snipped~~
* [x] New readme written and merged
* [x] Automation: ~~snipped info on GitHub Marketplace~~ GitLab CI now running on mirror: [recent pipelines](https://gitlab.com/TASVideos/BizHawk/pipelines), [latest `master` artifact](https://gitlab.com/TASVideos/BizHawk/-/jobs/artifacts/master/download?job=deploy_artifact). I also figured out how to [run xUnit tests](https://gitlab.com/YoshiRulz/BizHawk_CI_test/commit/cbd1a773236369b6af1e250d40a1268749d16ba4).
* [x] Bug report and feature request templates: [branch `issue-template`](https://github.com/TASVideos/BizHawk/tree/issue-template/.github/ISSUE_TEMPLATE)
* [x] Stale branches pruned
* [x] More labels created
	* All issues should be labelled with at least one of `App:`, `Core:`, `Ext. Tool:`, `Meta`, `Question/Support`, `re:` or `Tool:`. They're all coloured in **yellow or green** so you can tell at a glance what the main topic of the issue is. I've retroactively applied them as best I can.
	* Bugs should be labelled with `Repro:` labels if anything is known about the versions of EmuHawk which are or aren't affected (hopefully, that's all new issues). There are extra labels for comparing against upstream and for the stages of merging a patch.
	* There are some miscellaneous tags like `Enhancement` and `Homebrew`—it should be obvious when to use them, you just have to know that they exist in the first place.

**Comment by zeromus** [comment]
1. ACK
2. ACK
3. ACK
4. NAK - complete sentences. I prefer them.
5. Feel free to improve the readme by removing content and linking to the authoritative references on tasvideos. IMO the github page should be limited to showing how bizhawk works on github or details of how to collaborate, and how to find more information elsewhere. And shields. Here's a suggestion for a shield  [![SMB Romhacks Emulated](https://img.shields.io/badge/SMB%20Romhacks%20Emulated-12k-red.svg)](https://shields.io/) or more seriously  [![Consoles Supported](https://img.shields.io/badge/Consoles%20Supported%20-30-darkgreen.svg)]  or  [![TAS's Served](https://img.shields.io/badge/TAS's%20Served%20-300-darkgreen.svg)]. Related projects are fine on the wiki. Other notable forks on github or people using bizhawk for interesting things might be OK
6. NAK - I am philosophically opposed to style guides. But if there was one that enforced tabs, I would be interested.

**Comment by YoshiRulz** [comment]
Re: style enforcing, the [codefactor.io integration](https://github.com/marketplace/codefactor) runs StyleCop, [including indentation checks](https://i.imgur.com/Enu9tHY.png) (it says it uses `Settings.StyleCop` in the repo's root dir). It doesn't seem to author its own PRs. I also found [ImgBot](https://github.com/marketplace/imgbot).

**Comment by zeromus** [comment]
I was only half serious. I am also philosophically opposed to adding style checks to existing large projects, as it forces you to edit other people's code in order to get it to pass, thus ruining the history for no good reason. 
Looks like imgbot could save us 655KB or more. I'll set that up

**Comment by Sappharad** [comment]
If you don't already do it (I didn't check before posting this) you can just set project level defaults so that when people are working their Visual Studio automatically formats based on those:
https://docs.microsoft.com/en-us/visualstudio/ide/create-portable-custom-editor-options?view=vs-2017
No need to worry about checking other people's code. The only problem then is when you have people who hit format document on every single document they open which makes reviewing changes annoying when someone commits a 2 line change where they changed 600 lines because they formatted every file they looked at in the process.

**Comment by YoshiRulz** [comment]
Readme update is WIP at #1433: [live preview](https://github.com/YoshiRulz/BizHawk/blob/readme/README.md).

**Comment by YoshiRulz** [comment]
@zeromus I tried ImgBot and it says "Total -- 1,747.10kb -> 1,152.92kb (34.01%)" (for reference 2.3.1 is 126MiB uncompressed). It also removes a lot of the libpng warnings when building on Linux.

**Comment by YoshiRulz** [comment]
Also looked into StyleCop customisation and apparently it's using the "old" version and you can't set indentation.

**Comment by YoshiRulz** [comment]
With regards to enforcing code style:

VS and Rider support Roslyn analysers, so we can simply add Microsoft's StyleCop rewrite [from NuGet](https://www.nuget.org/packages/StyleCop.Analyzers/) and get most of the old version's functionality. I've set it up with just a few customisations in [branch `roslyn_test`](https://github.com/TASVideos/BizHawk/tree/roslyn_test); if anyone would like to go through every option and make a perfect config file, the docs are [here](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/Configuration.md).

**Comment by adelikat** [comment]
We already have a version controlled .DotSettings file for resharper that has the code styles we want to enforce.  

If you want this in Rider, set Rider to the same settings as this resharper file.

And we do not want errors or build failures on errors.  We can't and won't make code style mandatory.

**Comment by YoshiRulz** [comment]
I wrote a [bug report template](https://github.com/TASVideos/BizHawk/blob/issue-template/.github/ISSUE_TEMPLATE/bug_report.md), criticism welcome.

**Comment by adelikat** [comment]
The report should have them specify which system/core they were using.  That's highly likely to be relevant and very often not mentioned in bug reports
