### ISSUE TITLE
DiscoHawk meta-issue

### ISSUE THREAD

**Issue by YoshiRulz** [TASVideos/BizHawk#2535]
* [ ] `System.Web` dependency is superfluous (see #2261).
* [ ] `MainDiscoForm`'s icon is loaded from its `.resx` file, but non-string resources don't work anymore. It's easy enough to use an embedded image instead.
* [ ] Needs assembly load logic copied from EmuHawk's `Program`, or immediately crashes due to missing assembly `BizHawk.Common` on Linux.
* [ ] (optional) Remake the `Form` layouts using `*Ex` controls and FLPs.
* [ ] (optional) Move logic to library projects.

**Comment by adelikat** [comment]
@YoshiRulz : the problem is that discoHawk can not load in the BizHawk.Common library for some reason.  THerefore the OSTailoredCode can not be referenced which is required to do this correctly.  Better is to also import Client.Common so that we can just use PathUtils.ExeDirectoryPath

Can you look into this dll problem?

If you can look into that problem, we ca
